import {
    StyleFactory,
    APOLLO_BRIGHT_STYLE,
    ZEN_STYLE,
    TONER_STYLE,
    SATELLITE_STYLE,
    APOLLO_HYBRID_SATELLITE_STYLE
} from "./StyleFactory"

export {
    StyleFactory,
    APOLLO_BRIGHT_STYLE,
    ZEN_STYLE,
    TONER_STYLE,
    SATELLITE_STYLE,
    APOLLO_HYBRID_SATELLITE_STYLE
};